package com.exscudo.eon.peer.tasks;

import java.util.concurrent.atomic.AtomicBoolean;

import com.exscudo.eon.peer.data.Block;

public class AsyncState {

	class GeneratorState {

		/**
		 * Flag is set to <code>true</code> if the current node is synchronized
		 * with at least one remote node.
		 */
		private final AtomicBoolean isOutsideBlock = new AtomicBoolean();

		/**
		 * The last block generated by the node.
		 */
		volatile Block lastGeneratedBlock = null;

		void start() {
			isOutsideBlock.set(true);
		}

		boolean isStarted() {
			return isOutsideBlock.get();
		}

		void stop() {
			isOutsideBlock.set(false);
		}

	}

	final GeneratorState creator = new GeneratorState();
}
